### PR TITLE
Forcepoint Firewall: Python version upgrade

### PR DESCRIPTION
**Pull request by nikhileshcr-splunk**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [ ] Testing of all the changes has been performed (for bug fixes / features)
- [ ] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ ] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [ ] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [ ] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [x] Other (please describe): Upgrading app from py2 to py3. 

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  
## Release Notes (REQUIRED)
- Changed wheel dependencies from py2 to py3.
- Made syntactical changes to run the app in py3 environment. 

## What is the current behavior? (OPTIONAL)
- The app is archived and cannot be installed on SOAR. 

## What is the new behavior? (OPTIONAL)
- This upgrade will allow one to install app on SOAR. 

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by ighelani-crest** [comment]
Hi @nikhileshcr-splunk 
dev-requirements.txt is having pudb library. is it necessary or should I remove it?

**Comment by nikhileshcr-splunk** [comment]
Hi @ighelani-crest,
I removed it. I believe SOAR has it by default.

**Comment by ighelani-crest** [comment]
Thanks @nikhileshcr-splunk !

**Comment by ighelani-crest** [comment]
Hi @nikhileshcr-splunk 
As per our best practices, we change the major version when we transfer from python2 to python3. As you have changed the app name and product name, I have added them in the release notes. 
Let me know if you have any concerns.

**Comment by nikhileshcr-splunk** [comment]
Hi @ighelani-crest,
Looks good to me! Thanks

**Comment by ighelani-crest** [comment]
Hi @nikhileshcr-splunk 
I have found the some observation in your app's code.

- Need to change license year in Json and license file [conflicting in both files]

Connector file :

- Add line 84 before line no 82
- Add condition for checking if login is successful or not for block IP action after line  no 83
- Line no 134 and 135 never called [dead code], I think we need to remove line no 133 and line 134 or dead code [line no - 134, 135]

Can you please make changes according to the observation?

**Comment by nikhileshcr-splunk** [comment]
Hi @ighelani-crest,
Apologies for the oversight! I've made the changes as per your suggestions. Thanks

**Review by mmomin-crest — APPROVED** [review]

**Review by dhwanis-crest — APPROVED** [review]

**Review by ishans-crest — APPROVED** [review]

**Pull request merged**
